"""
Git helper utilities for GitHub MCP integration.

This module provides helper functions for generating branch names, commit messages,
PR descriptions, and .gitignore files. The actual Git operations are performed
by the GitHub MCP Server tools directly used by the agent.

GitHub MCP Tools used by the agent:
- mcp__github__create_repository
- mcp__github__create_branch
- mcp__github__push_files
- mcp__github__create_pull_request
- mcp__github__create_or_update_file
- mcp__github__get_file_contents
- mcp__github__list_branches
"""
from typing import Dict, Any, Optional, List
from pathlib import Path

from backend.config import settings


def generate_branch_name(
    project_name: str, 
    page_name: Optional[str] = None
) -> str:
    """
    Generate a branch name for the project.
    
    Args:
        project_name: Name of the project
        page_name: Optional page name for multi-page projects
        
    Returns:
        Branch name (e.g., "feature/my-project" or "feature/my-project/about-page")
    """
    # Clean project name
    clean_name = project_name.lower().replace(" ", "-")
    clean_name = "".join(c for c in clean_name if c.isalnum() or c == "-")
    
    if page_name:
        clean_page = page_name.lower().replace(" ", "-")
        clean_page = "".join(c for c in clean_page if c.isalnum() or c == "-")
        return f"feature/{clean_name}/{clean_page}"
    
    return f"feature/{clean_name}"


def generate_commit_message(
    change_type: str,
    component_name: Optional[str] = None,
    description: str = ""
) -> str:
    """
    Generate a semantic commit message.
    
    Args:
        change_type: Type of change (feat, fix, style, refactor, etc.)
        component_name: Optional component/page name
        description: Description of the change
        
    Returns:
        Semantic commit message
    """
    scope = "(figma)"
    if component_name:
        clean_name = component_name.replace(" ", "-").lower()
        return f"{change_type}{scope}: Add {clean_name}"
    
    return f"{change_type}{scope}: {description}"


def generate_pr_description(
    project_name: str,
    components: List[str],
    figma_url: Optional[str] = None,
    accessibility_status: Optional[Dict[str, Any]] = None,
    build_status: Optional[Dict[str, Any]] = None
) -> str:
    """
    Generate a pull request description.
    
    Args:
        project_name: Name of the project
        components: List of component names created
        figma_url: Optional Figma design URL
        accessibility_status: Optional accessibility check results
        build_status: Optional build check results
        
    Returns:
        Pull request description in Markdown format
    """
    pr_body = f"""## Figma to React Conversion: {project_name}

### Summary
This PR contains React components automatically generated from Figma design.

"""
    
    if figma_url:
        pr_body += f"**Figma Design:** [{figma_url}]({figma_url})\n\n"
    
    if components:
        pr_body += "### Components Created\n"
        for component in components:
            pr_body += f"- `{component}`\n"
        pr_body += "\n"
    
    if accessibility_status:
        status_icon = "✅" if accessibility_status.get("passes_aa") else "⚠️"
        pr_body += f"### Accessibility Status {status_icon}\n"
        pr_body += f"- WCAG AA Compliance: {'Pass' if accessibility_status.get('passes_aa') else 'Review needed'}\n"
        pr_body += f"- ARIA Roles: {'Added' if accessibility_status.get('has_aria') else 'Review needed'}\n"
        pr_body += f"- Alt Text: {'Present' if accessibility_status.get('has_alt_text') else 'Review needed'}\n\n"
    
    if build_status:
        status_icon = "✅" if build_status.get("success") else "❌"
        pr_body += f"### Build Status {status_icon}\n"
        pr_body += f"- Build: {'Success' if build_status.get('success') else 'Failed'}\n"
        if build_status.get("bundle_size"):
            pr_body += f"- Bundle Size: {build_status['bundle_size'].get('total_kb', 'N/A')} KB\n"
        pr_body += "\n"
    
    pr_body += """### Review Checklist
- [ ] Design matches Figma
- [ ] Responsive on all screen sizes
- [ ] Accessibility checks pass
- [ ] Build succeeds
- [ ] ESLint passes
- [ ] Code follows project conventions

### Testing
- [ ] Desktop view tested
- [ ] Mobile view tested
- [ ] Keyboard navigation tested
- [ ] Screen reader tested

---
*Generated by Aura Agent*
"""
    
    return pr_body


def generate_gitignore() -> str:
    """
    Generate a .gitignore file content for React projects.
    
    Returns:
        .gitignore file content
    """
    return """# Dependencies
node_modules/
.pnp/
.pnp.js

# Build
dist/
build/
out/
.next/

# Cache
.cache/
*.tsbuildinfo

# Environment
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Logs
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Editor
.vscode/
.idea/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# Testing
coverage/
.nyc_output/

# Misc
*.local

# Screenshots (generated during visual verification)
screenshots/
"""


def get_github_owner() -> str:
    """Get configured GitHub owner from settings."""
    return settings.github_owner


def get_github_default_branch() -> str:
    """Get configured default branch from settings."""
    return settings.github_default_branch


def is_github_enabled() -> bool:
    """Check if GitHub integration is enabled."""
    return bool(settings.effective_github_token and settings.auto_create_repo)


def get_repo_creation_params(
    project_name: str,
    description: str = "",
    private: bool = True
) -> Dict[str, Any]:
    """
    Generate parameters for GitHub MCP create_repository tool.
    
    Args:
        project_name: Name of the repository
        description: Repository description
        private: Whether the repo should be private
        
    Returns:
        Dictionary of parameters for MCP tool
    """
    params = {
        "name": project_name,
        "description": description or f"React project generated from Figma design",
        "private": private,
        "autoInit": False,
    }
    
    if settings.github_owner:
        params["organization"] = settings.github_owner
    
    return params


def get_push_files_params(
    repo: str,
    files: List[Dict[str, str]],
    branch: str = "main",
    commit_message: str = "feat(figma): Initial project from Figma design"
) -> Dict[str, Any]:
    """
    Generate parameters for GitHub MCP push_files tool.
    
    Args:
        repo: Repository name
        files: List of file objects with 'path' and 'content'
        branch: Branch to push to
        commit_message: Commit message
        
    Returns:
        Dictionary of parameters for MCP tool
    """
    return {
        "owner": settings.github_owner,
        "repo": repo,
        "branch": branch,
        "files": files,
        "message": commit_message,
    }


def get_pr_creation_params(
    repo: str,
    title: str,
    body: str,
    head: str,
    base: str = "main",
    draft: bool = False
) -> Dict[str, Any]:
    """
    Generate parameters for GitHub MCP create_pull_request tool.
    
    Args:
        repo: Repository name
        title: PR title
        body: PR body/description
        head: Head branch (source)
        base: Base branch (target)
        draft: Whether to create as draft
        
    Returns:
        Dictionary of parameters for MCP tool
    """
    return {
        "owner": settings.github_owner,
        "repo": repo,
        "title": title,
        "body": body,
        "head": head,
        "base": base,
        "draft": draft,
    }
